-- For emergency purposes such as resetting the database/catalog

USE `ilocos_sur`;

-- Clear the catalog, then reload.
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM items;
DELETE FROM categories;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO categories (slug, title, tagline, sort_order) VALUES
    ('food', 'Food', 'Ilocano delicacies that will satisfy your cuisine curiosity', 0),
    ('beach', 'Beach', 'Breathtaking coves and golden shorelines', 1),
    ('historical', 'Historical / Educational', 'Where Spanish-colonial heritage still stands', 2),
    ('church', 'Church / Religious', 'Centuries-old faith in stone and brick', 3),
    ('arts', 'Arts, Crafts & Culture', 'Showcases the artistic heritage of the province', 4),
    ('festivals', 'Festivals & Events', 'The province at its most colorful', 5),
    ('nature', 'Nature & Adventure', 'Beautiful landscapes and waterforms that tourists must explore', 6),
    ('pasalubong', 'Pasalubong (Souvenirs)', 'Take a piece of Ilocos Sur home', 7),
    ('stay', 'Where to Stay', 'Heritage inns and modern comfort', 8),
    ('transportation', 'Getting Around', 'Calesa, tricycle, jeepney, and beyond', 9);

INSERT INTO items
    (id, category_slug, name, location, summary, about, tags_json, image, sort_order) VALUES
    ('vigan-empanada', 'food', 'Vigan Empanada', 'Throughout Ilocos Sur, especially around Plaza Burgos and Calle Crisologo in Vigan City.', 'A crisp rice-flour shell stuffed with grated green papaya, Vigan longganisa, and a whole egg, deep-fried to order.', 'The Vigan empanada is the city''s most famous street food, cooked fresh in front of you at the stalls ringing Plaza Burgos. Unlike the Western pastry empanada, this version uses a rice-flour dough tinted orange with achuete (annatto). It is filled with grated unripe papaya, mongo beans, the garlicky local longganisa, and a cracked egg, then folded and fried until shatteringly crisp. It is served piping hot with a splash of sukang Iloko (sugarcane vinegar) spiked with chili and garlic.', '["street food", "savory snack", "must-try"]', 'app-images/ViganEmpanada.jpg', 0),
    ('bagnet', 'food', 'Bagnet', 'Throughout Ilocos Sur, especially in the Narvacan Public Market, widely considered the capital of bagnet. Also served in many Vigan restaurants like Cafe Leona, Hidden Garden''s Lilong and Lilang Restaurant, and Comida Del Norte.', 'Pork belly boiled, air-dried, then double-deep-fried into glassy, crackling crisp skin over tender meat.', 'Bagnet is the Ilocano answer to crispy pork. The belly is simmered with salt and aromatics, dried, then fried twice so the skin blisters into a brittle, popcorn-like crunch while the meat stays moist. It is the heart of pinakbet and dinengdeng, but is just as happily eaten on its own dunked in KBL (kamatis-bagoong-lasona: tomato, fermented fish paste, and shallots).', '["crispy pork belly", "ilocano classic", "must-try"]', NULL, 1),
    ('vigan-longganisa', 'food', 'Vigan Longganisa', 'Vigan City Public Market; restaurants and carinderias across Vigan', 'A small, plump pork sausage known for its intense garlicky flavor and tangy taste.', 'Vigan longganisa is a de recado sausage noted for its salty, garlicky, and sour flavor, influenced by Mexican chorizo. Made from coarsely ground pork packed with local garlic, it is seasoned with vinegar (giving its tang), brown sugar, black pepper, and annatto, then air-dried. It stars in longsilog (with garlic rice and egg) and is dipped in sukang Iloko. Celebrated every January at the Vigan Longganisa Festival.', '["sausage", "breakfast", "pasalubong"]', NULL, 2),
    ('sinanglao', 'food', 'Sinanglaw', 'Local eateries and carinderias in Vigan City', 'A sour, beefy soup of innards brightened with kamias and bile, eaten at sunrise.', 'Sinanglaw is a breakfast soup of beef tripe and innards simmered until tender in a tart broth soured with kamias and deepened with a touch of bile. Served steaming with rice, it is often enjoyed as a pulutan (drinking snack). Good sinanglaw takes about four hours to simmer and is traditional morning fare alongside Vigan''s garlicky longganisa.', '["soup", "breakfast", "local favorite"]', NULL, 3),
    ('pinakbet', 'food', 'Pinakbet', 'Everywhere in Ilocos Sur – home kitchens, restaurants, carinderias', 'The original Ilocano vegetable stew bound with bagoong isda and crowned with bagnet.', 'Pinakbet (from pinakebbet, "to shrivel") is the quintessential Ilocano vegetable stew. Bitter melon, eggplant, okra, squash, long beans, and tomatoes are stewed with bagoong isda (fermented fish paste) and topped with bagnet. Traditionally cooked in a palayok (clay pot) over low heat, it is served hot, often with grilled or fried fish.', '["vegetable", "stew", "classic"]', NULL, 4),
    ('royal-bibingka', 'food', 'Royal Bibingka', 'Vigan City specialty bakeries and pasalubong shops, such as Tongson''s near Plaza Burgos', 'A dense, buttery, sticky-rice cake with a caramelized cheese top, sold warm in slabs.', 'Royal bibingka is the signature rice cake (kakanin) of Vigan City. Unlike the soft, fluffy bibingkang galapong common in Manila, this Ilocano version is made from glutinous rice flour, which gives it a characteristically sticky, dense, and chewy texture. It is often baked in a large pan or as cupcake-sized portions, and slathered with a generous layer of melted cheese that caramelizes on top to form a sweet, savory crust. A sweet and satisfying snack, it is sold as a popular pasalubong and is best enjoyed warm with a hot cup of coffee or salabat (ginger tea).', '["dessert", "rice cake", "pasalubong", "must-try"]', NULL, 5),
    ('okoy-tiyosko', 'food', 'Okoy Tiyosko', 'Street vendors in Vigan''s plaza area (Empanadahan)', 'Crispy shrimp and vegetable fritters made with tiny freshwater shrimp, squash, and bean sprouts.', 'Okoy Tiyosko is the Ilocano crispy shrimp fritter, made extra thin and brittle using tiyosko (small, sun-dried shrimp). The batter includes grated kalabasa (squash), mongo sprouts, and kutchay (Chinese chives), then deep-fried in a wok in a circular motion to achieve an airy, lacy crispness. Served hot with sukang Iloko spiked with chili and garlic, it is a popular afternoon snack or pulutan.', '["fritter", "snack", "shrimp", "crispy"]', NULL, 6),
    ('poqui-poqui', 'food', 'Poqui Poqui', 'Local carinderias and restaurants across Ilocos Sur', 'A scrambled egg dish with grilled eggplant, tomatoes, and onions – Ilocano comfort food at its simplest.', 'Poqui Poqui is a humble Ilocano breakfast scramble. Grilled eggplants are roasted over an open flame until smoky, then peeled, mashed, and sautéed with garlic, onions, and diced tomatoes before being scrambled with eggs. The result is soft, savory, and slightly smoky. Often served as a side to fried fish or bagnet, it also stands alone as a vegetarian meal, seasoned simply with patis (fish sauce).', '["breakfast", "egg", "vegetarian", "comfort food"]', NULL, 7),
    ('mindoro-beach', 'beach', 'Mindoro Beach', 'Brgy. Mindoro, Vigan City, Ilocos Sur', 'Vigan City''s own dark-sand coastline with strong waves popular among surfers.', 'Mindoro Beach is Vigan''s only coastal destination, known for its unique black sand rich in magnetite (iron ore). It offers powerful waves ideal for surfing, though swimming is only recommended when waters are calm. It provides a raw, undeveloped coastal experience, perfect for sunset viewing away from crowds.', '["beach", "black sand", "surfing", "swimming", "sunset"]', NULL, 0),
    ('pug-os-cove', 'beach', 'Pug-os Cove', 'Brgy. Pug-os, Cabugao, Ilocos Sur', 'A family-friendly cove with fine white sand and shallow, gradually sloping waters.', 'Pug-os Cove is often considered the best beach in Ilocos Sur. Its white sand cove features a gently sloping seabed, making it safe for children and non-swimmers. The beach is also a center for traditional sea salt production, and is only a 30-minute drive from Vigan City, with a new access road completed in 2025.', '["beach", "white sand", "family-friendly", "swimming", "picnic"]', NULL, 1),
    ('santiago-cove', 'beach', 'Santiago Cove', 'Sabangan, Santiago, Ilocos Sur', 'A stunning white-sand cove framed by rolling hills, dubbed the "Boracay of the North."', 'Santiago Cove is the fastest-growing tourism hub in Ilocos Sur. Its kilometer-long coastline of fine white sand is framed by rolling hills. It is home to high-end resorts like Vitalis Villas and Santiago Cove Hotel and was officially declared a tourist destination by the Philippine government in 2019.', '["beach", "white sand", "resort", "swimming", "scenic"]', NULL, 2),
    ('darapidap-beach', 'beach', 'Darapidap Beach', 'Barangay Darapidap, Candon City, Ilocos Sur', 'A beach of unique volcanic black sand, known for its strong waves perfect for surfing and skimboarding.', 'Darapidap Beach in Candon City stretches for 900 meters along Ilocos Sur''s 16-kilometer coastline. It features striking black sand, a result of its volcanic origins. The strong, rolling waves are a magnet for surfers and skimboarders. The area is now a developed tourism zone, complete with a seaside plaza, the scenic Darapidap-Paypayad Hanging Bridge, and is near the new Candon City Aquarium and Park.', '["beach", "black sand", "surfing", "skimboarding"]', NULL, 3),
    ('sulvec-beach', 'beach', 'Sulvec Beach', 'Barangay Sulvec, Narvacan, Ilocos Sur', 'A scenic stretch of brown sand and rocky coastline, famous for its breathtaking sunsets.', 'The coastline at Sulvec is a charming mix of wide, brown sandy shores and dramatic rock formations, which has drawn comparisons to the beaches of Monterey, California. The area''s beauty is best captured in photographs, especially during its spectacular sunsets. Located here is the iconic "Paraiso ni Juan" grotto and the historic Sulvec Watchtower, a brick structure built by the Spanish to warn locals of incoming pirate attacks.', '["beach", "brown sand", "rocky shoreline", "sunset view", "historical"]', NULL, 4),
    ('suso-beach', 'beach', 'Suso Beach', 'Barangay Suso, Santa Maria, Ilocos Sur', 'A beautiful public beach known for its relaxed atmosphere, golden sunsets, and the unique, legend-rich hills that flank its shores.', 'Suso Beach offers a relaxing and easily accessible coastal escape right along the main highway. Its waters mix rocky patches with stretches of light sand, providing a refreshing ocean view against a backdrop of lush hills. According to Ilocano folklore, these hills were shaped by the giant Angalo, who sculpted the land to honor the memory of a local figure, giving the beach its unique name and mystique. It''s the perfect spot for a quick, scenic stop to unwind and take photos.', '["beach", "white sand", "scenic views", "sunset view", "local folklore"]', NULL, 5),
    ('calle-crisologo', 'historical', 'Calle Crisologo', 'Crisologo Street, Vigan City, Ilocos Sur', 'The iconic cobblestone street of Spanish-colonial mansions, a UNESCO World Heritage core.', 'Calle Crisologo is the beating heart of Vigan and the image that defines the city: a cobblestone street lined with preserved bahay-na-bato mansions from the Spanish colonial era, their capiz-shell windows and wooden balconies intact. Closed to most traffic, it is best explored on foot or by calesa, especially at dawn or after the lanterns are lit.', '["unesco", "heritage", "iconic", "cobblestone", "must-see"]', NULL, 0),
    ('syquia-mansion', 'historical', 'Syquia Mansion', 'Quirino Boulevard, Vigan City, Ilocos Sur', 'The ancestral home of President Elpidio Quirino, preserved as a house museum.', 'The Syquia Mansion is a grand 19th-century bahay na bato that belonged to the family of President Elpidio Quirino''s wife. Now a museum, it preserves period furniture, portraits, and presidential memorabilia, offering a window into the lives of Vigan''s wealthy mestizo families.', '["museum", "presidential", "ancestral home", "heritage"]', NULL, 1),
    ('crisologo-museum', 'historical', 'Crisologo Museum', 'A. Reyes Street, Vigan City, Ilocos Sur', 'A family museum honoring the political legacy of Congressman Floro Crisologo.', 'Housed in the ancestral home of the prominent Crisologo political clan, this museum chronicles the life and assassination of Congressman Floro Crisologo. Exhibits include personal memorabilia, antique furniture, and historical documents. Entry is by donation.', '["museum", "history", "political", "free entry"]', NULL, 2),
    ('plaza-salcedo', 'historical', 'Plaza Salcedo', 'Vigan City, Ilocos Sur', 'An oblong plaza named for Juan de Salcedo, home to the dancing fountain show.', 'Plaza Salcedo is the older of Vigan''s two main plazas, named after Spanish conquistador Juan de Salcedo who founded the city. By day it frames the cathedral and provincial capitol; by night it hosts a free dancing fountain light-and-water show that draws crowds. It is also the execution site of revolutionary leader Gabriela Silang.', '["plaza", "fountain show", "landmark", "free entry"]', NULL, 3),
    ('vigan-cathedral', 'church', 'St. Paul Metropolitan Cathedral (Vigan Cathedral)', 'Burgos Street, Vigan City, Ilocos Sur', 'A 19th-century earthquake-baroque cathedral and the seat of the Archdiocese of Nueva Segovia.', 'Also known as Vigan Cathedral, this Renaissance and earthquake-baroque style church was completed in 1800. It anchors Plaza Salcedo and is part of the UNESCO World Heritage City of Vigan, having been founded by the Spanish in 1575. Despite damage from the 2022 earthquake, the cathedral remains the symbolic and ecclesiastical heart of the province.', '["cathedral", "baroque", "unesco", "landmark"]', NULL, 0),
    ('santa-maria-church', 'church', 'Santa Maria Church', 'Santa Maria, Ilocos Sur', 'A magnificent hilltop fortress-church and UNESCO World Heritage Site, now a Minor Basilica.', 'Built by Augustinians in 1765, this Roman Catholic shrine was designated a UNESCO World Heritage Site in 1993 as one of the Philippines'' four Baroque churches. Its unique fortress-like structure is reached by an 85-step granite staircase. In August 2025, it was formally elevated to the status of a Minor Basilica.', '["unesco", "baroque", "hilltop", "minor basilica"]', NULL, 1),
    ('bantay-bell-tower', 'church', 'Bantay Bell Tower', 'Bantay, Ilocos Sur', 'A historic 16th-century watchtower and belfry offering panoramic views of the surrounding countryside.', 'Standing atop a hill just minutes from Vigan, this red-brick tower was originally built in 1591-92 as a lookout to warn the town of pirate attacks. A short climb rewards visitors with a panoramic view of the mountains, the town of Bantay, and the Mestizo River. It is arguably the most recognizable landmark in Ilocos Sur after Calle Crisologo.', '["bell tower", "viewpoint", "historical", "heritage"]', NULL, 2),
    ('magsingal-church', 'church', 'Magsingal Church', 'Manila North Road, Magsingal, Ilocos Sur', 'A 19th-century Baroque church recognized as a National Cultural Treasure.', 'The present church was built in 1827, replacing an earlier structure destroyed by an earthquake in 1723. It was declared a National Cultural Treasure in 2001. The church complex features an intricate retablo and houses a museum displaying Ilocano religious and cultural artifacts. It is a popular stop for heritage tours and history buffs in the province.', '["national cultural treasure", "baroque", "heritage", "museum"]', NULL, 3),
    ('pagburnayan', 'arts', 'Pagburnayan Pottery', 'Barangay Pagburnayan, Vigan City, Ilocos Sur (Southwest part of the city, a short walk or tricycle ride from Calle Crisologo)', 'A living heritage village where artisans mold clay into traditional earthenware jars using centuries-old techniques.', 'A visit to Pagburnayan is like stepping into a living museum. Known as burnay, these distinctive earthenware jars are still crafted by hand using methods introduced by Chinese immigrants in the pre-colonial era. Local clay is mixed with fine sand and skillfully shaped on a foot-powered potter''s wheel, then fired in traditional ground kilns to achieve a characteristic hard, reddish-brown finish. Visitors can watch master potters at work and are even encouraged to try shaping their own jar, making for a unique, hands-on souvenir.', '["pottery", "living heritage", "hands-on", "burnay", "traditional craft"]', NULL, 0),
    ('abel-weaving', 'arts', 'Abel Iloko Weaving', 'Weaving centers across Ilocos Sur, particularly in Vigan, Santiago, Santa, and Bantay', 'A centuries-old weaving tradition producing durable, handwoven fabric with distinct Ilocano geometric patterns.', 'Abel Iloko, also known as Inabel, is a weaving tradition deeply rooted in the cultural fabric of the Ilocos region. The term comes from the Ilocano verb "abel," meaning to weave. Using large wooden pedal looms, skilled weavers create soft yet durable textiles celebrated for their austere geometric designs, making them sought after for fashion and interior design. These vibrant blankets, towels, and table runners are a perfect representation of Ilocano resourcefulness and creativity and make a meaningful souvenir to support local artisans.', '["weaving", "heritage textile", "traditional craft", "inabel", "handmade"]', NULL, 1),
    ('hidden-garden', 'arts', 'Hidden Garden', 'Katipunan Street, Barangay Bulala, Vigan City, Ilocos Sur', 'A lush garden sanctuary offering a peaceful retreat with native plants, an Ilocano restaurant, and a souvenir shop.', 'Hidden Garden is a serene spot that serves as a meeting point for exquisite cuisine, nature, and local crafts. It features a sprawling landscape of native and exotic plants, a restaurant serving authentic Ilocano dishes like bagnet, a coffee shop, and a shop selling local handicrafts, plants, and pasalubong. With no entrance fee, it''s a popular stop for travelers looking to enjoy a relaxing meal and stroll in a beautifully curated, tropical environment.', '["garden", "nature", "dining", "souvenir shopping"]', NULL, 2),
    ('santa-blade-crafts', 'arts', 'Santa Blade Crafts', 'Santa, Ilocos Sur', 'The primary source of authentic, handcrafted Ilocano knives and bolos, forged by traditional blacksmiths known as panday.', 'The town of Santa is the heart of the province''s blade-making industry, where blades are distributed across the region. The knives are typically forged from recycled truck leaf springs using traditional methods, and their handles are made from carabao horn. A common collector''s item is the "Santa knife," which is recognizable by its soldier''s head pommel. While you can sometimes buy directly from the artisans, it''s best to visit antique and souvenir shops in Vigan City for a more curated experience.', '["bladesmithing", "traditional craft", "panday", "collector''s item"]', NULL, 3),
    ('binatbatan-festival', 'festivals', 'Viva Vigan Binatbatan Festival', 'Throughout Vigan City, Ilocos Sur', 'A week-long May festival celebrating Vigan''s weaving heritage with colorful street dancing and art exhibits.', 'Held every first week of May, this festival''s name comes from the traditional process of beating cotton pods to separate fibers for abel cloth. During the festival, the historic district transforms into a vibrant stage for street dance competitions, art exhibits, and trade fairs. Participants wear colorful woven costumes as they perform dances that tell stories of Vigan''s history.', '["street dance", "abel weaving", "arts", "may"]', NULL, 0),
    ('longganisa-festival', 'festivals', 'Vigan Longganisa Festival', 'Plaza Burgos and surrounding areas, Vigan City, Ilocos Sur', 'A January food festival honoring Vigan''s famous garlicky sausage with parades and cooking contests.', 'Celebrated every January, this festival coincides with Vigan''s cityhood anniversary and town fiesta. Highlights include a grand parade, street dancing, the "Reynas de Vigan" pageant, and a longganisa-themed culinary contest. Local producers also showcase their products at a trade expo.', '["food", "sausage", "heritage cuisine", "january"]', NULL, 1),
    ('kannawidan-festival', 'festivals', 'Kannawidan Ylocos Festival', 'Province-wide, with main events in Vigan City, Ilocos Sur', 'The province-wide founding anniversary festival celebrating Ilocano heritage, traditions, and artistry.', 'Held every late January to early February, Kannawidan commemorates the founding of Ilocos Sur as a separate province on February 2, 1818. The festival opens with a mass and procession of patron saints. Activities include street dancing, a tattoo expo, art competitions, a trade and agri-fair, a beauty pageant, concerts, and a period party where guests wear Spanish-colonial attire.', '["provincial foundation", "cultural showcase", "street dancing", "tattoo expo"]', NULL, 2),
    ('raniag-festival', 'festivals', 'Raniag Twilight Festival', 'Vigan City, Ilocos Sur (Calle Crisologo, Plaza Burgos, Mestizo River)', 'A unique Halloween festival honoring departed loved ones with lights, floats, and candle-lit festivities.', 'Held every last week of October until November 2, "Raniag" means bright light in Ilocano. The festival, which began in 2010, features a grand float parade along Calle Crisologo, a horror house attraction, street dancing, and a candle-lighting ceremony for the departed. Once featuring candle floating on the Mestizo River, the event blends solemn remembrance with a festive and quirky spirit.', '["halloween", "undas", "lights", "float parade", "night festival"]', NULL, 3),
    ('pinsal-falls', 'nature', 'Pinsal Falls', 'Baballasioan, Santa Maria, Ilocos Sur', 'The tallest waterfall in Ilocos Sur, cascading 85 feet into a turquoise pool.', 'Nestled in the mountains of Santa Maria, Pinsal Falls is one of the largest and most stunning waterfalls in the Ilocos Region. Its 85-foot cascade plunges into a narrow gorge, surrounded by unique rock formations. According to Ilocano mythology, the falls and its natural pools were formed by the giant Angalo as he searched for his wife, leaving behind his massive footprint known as "Tugot ni Angalo". The site has been legally declared a tourist destination, ensuring its development and preservation for visitors. You can take a dip in the cool waters or rent a raft to get closer to the cascading water.', '["waterfall", "swimming", "folklore", "nature"]', NULL, 0),
    ('tirad-pass', 'nature', 'Tirad Pass (Tirad Pass National Shrine)', 'Gregorio del Pilar, Ilocos Sur', 'A historic mountain pass and shrine commemorating the last stand of General Gregorio del Pilar.', 'Tirad Pass is the hallowed site where the young "Boy General" Gregorio del Pilar made his valiant final stand, delaying American forces to cover President Emilio Aguinaldo''s retreat in 1899. It is the most famous tourist attraction in its namesake municipality. Today, a shrine and monument mark the location. Reaching the site involves a scenic 4.5-kilometer trek, which can take about two hours from the municipal hall, passing by the historic Spanish Trail.', '["historical", "world war ii", "shrine", "hiking"]', NULL, 1),
    ('quirino-bridge', 'nature', 'Quirino (Banaoang) Bridge', 'Barangay Banaoang, Santa, Ilocos Sur (spanning the Abra River to Bantay)', 'A 456-meter-long historic steel arch bridge, now a popular tourist landmark for its stunning views.', 'Built in 1931 during the American colonial period, this iconic bridge spans the Abra River, connecting the towns of Santa and Bantay. Originally called the Banaoang Bridge, it was later named after President Elpidio Quirino of Ilocos Sur. While a newer bridge has taken over vehicular traffic, the old structure has been preserved as a tourist attraction for its beautiful architecture and breathtaking scenery of the river and surrounding mountains.', '["bridge", "historical", "architecture", "scenic"]', NULL, 2),
    ('banaoang-viewdeck', 'nature', 'Banaoang Viewdeck', 'National Highway, Santa, Ilocos Sur', 'A roadside viewing deck offering a dramatic view of the Quirino Bridge and the Abra River.', 'Located right beside the old Quirino Bridge, this simple but popular stopover offers one of the most dramatic views in the province. From this vantage point, you can capture stunning panoramic photos of the bridge''s elegant arches, the broad, winding Abra River, and the mountainous backdrop of the Ilocos Range. It is a perfect spot to stretch your legs and appreciate the beauty of Ilocos Sur''s landscape.', '["viewpoint", "photo spot", "scenic", "must-stop"]', NULL, 3),
    ('baluarte-zoo', 'nature', 'Baluarte Zoo (Baluarte Resort and Mini Zoo)', 'Quirino Boulevard, Tamag, Vigan City, Ilocos Sur', 'An 80-hectare zoological park and resort with exotic animals and a safari gallery.', 'Founded by former Ilocos Sur governor Chavit Singson, Baluarte is a popular destination for families. Its mini zoo is home to a wide variety of exotic animals, including white lions, Bengal tigers, zebras, and ostriches. Visitors can explore the grounds for free, though there are fees for special tours and interactions. The complex also features a safari gallery with taxidermy displays, a chapel, and a restaurant.', '["zoo", "safari", "wildlife", "family-friendly", "free admission"]', NULL, 4),
    ('aw-asen-falls', 'nature', 'Aw-asen Falls', 'Barangay Santo Rosario, Sigay, Ilocos Sur', 'The tallest waterfall in the Ilocos Region, plunging 120 meters into a deep, pristine pool.', 'Aw-asen Falls is the crown jewel of Sigay''s rugged mountains. Reaching it requires a 45-minute trek through rice fields, river crossings, and mountain trails. The effort rewards visitors with breathtaking views of a towering cascade that flows year-round, even during the dry season. Environmental fee is P50 plus optional guide fee.', '["waterfall", "hiking", "tallest falls", "must-see", "remote"]', NULL, 5),
    ('caniaw-forest-park', 'nature', 'Caniaw Heritage and Forest Park', 'Barangay Taleb, Bantay, Ilocos Sur', 'An eco-adventure park offering ziplines, rope courses, wall climbing, and scenic forest walks.', 'Just a 10-minute drive from Bantay highway, Caniaw is an agro-eco tourism destination featuring a roller coaster zipline, challenging rope courses, wall climbing, mountain tubing, and biking trails. Entrance is P75 for adults, P50 for children, with activity fees from P50 to P750. Group packages are also available.', '["adventure park", "zipline", "rope course", "nature trails", "family-friendly"]', NULL, 6),
    ('sukang-iloko', 'pasalubong', 'Sukang Iloko', 'Vigan Public Market, souvenir shops along Calle Crisologo, Alilem, and Sta. Maria.', 'Naturally fermented sugarcane vinegar with a mellow, distinctively fresh taste.', 'Sukang Iloko, produced using an old tradition, is made by fermenting sugarcane and using Ilocano wine (basi) as a base. It''s more mellow compared to rice vinegar because of its fresher taste. Often aged in traditional burnay jars, it is the quintessential dip for Ilocos Sur''s famous empanada and bagnet.', '["vinegar", "fermented", "pantry essential"]', NULL, 0),
    ('abel-products', 'pasalubong', 'Abel Woven Goods', 'Hand-loom weaving centers and shops in Bantay, Caoayan, Santiago, and Calle Crisologo.', 'Traditional hand-loomed fabric known for its strength and vibrant colors.', 'Abel is a traditional product of the Ilocos region, made from yarns of cotton or sagut. It''s a fabric known to be strong and colorful and is woven into items like towels, throws, home decor, and clothing.', '["weaving", "textile", "hand-loom"]', NULL, 1),
    ('burnay-jars', 'pasalubong', 'Burnay Jars', 'Pagburnayan Jar Factory / RG Jar Factory in Vigan City.', 'Hand-crafted earthenware jars used traditionally for storing water, vinegar, or basi.', 'Local artisans shape clay into beautiful earthenware jars using time-honored techniques. A visit to Pagburnayan is like stepping into a living museum. The jars are both artistic and functional, often used to store water, vinegar, or basi (local sugarcane wine).', '["pottery", "earthenware", "functional art"]', NULL, 2),
    ('chichacorn', 'pasalubong', 'Chichacorn', 'Widely available at souvenir shops and markets throughout Vigan City and Candon.', 'Ilocos'' unique version of cornick that is crunchy yet softer than the traditional snack.', 'A popular and "highly addictive" Ilocos pasalubong. Chichacorn is Ilocos'' version of cornicks (deep-fried corn kernels) but "better—they''re softer while still retaining their crunchiness". It''s a true Filipino classic snack from Ilocos.', '["snack", "crispy", "garlicky"]', NULL, 3),
    ('hotel-luna', 'stay', 'Hotel Luna', 'De Los Reyes St, Vigan City, Ilocos Sur', 'The Philippines'' first museum-hotel, blending heritage charm with modern luxury and a vast art collection.', 'Opened in 2014, Hotel Luna is a unique 4-star hotel that also functions as an art museum. It houses an impressive collection, including works by the master painter Juan Luna. The hotel offers a rooftop pool and is just a four-minute walk from the famous Calle Crisologo, providing a perfect base for exploring Vigan''s historic district.', '["museum-hotel", "heritage", "luxury", "must-stay"]', NULL, 0),
    ('ciudad-fernandina', 'stay', 'Ciudad Fernandina Hotel', '26 Plaridel Street, corner Mabini Street, Vigan City, Ilocos Sur', 'A well-located heritage-style hotel offering modern comforts and a complimentary breakfast featuring Ilocano classics.', 'This hotel is celebrated for its convenient location, placing guests just a few steps from Calle Crisologo and the Crisologo Museum. It is particularly noted for its delightful complimentary breakfast, which serves local favorites like Vigan longganisa, bagnet, and poqui-poqui, offering a delicious taste of the province.', '["heritage-style", "central", "breakfast included"]', NULL, 1),
    ('grandpas-inn', 'stay', 'Grandpa''s Inn', '1 Bonifacio Street corner Quirino Boulevard, Vigan City, Ilocos Sur', 'A charming, budget-friendly inn in an 1850s ancestral house, filled with antiques and old-world character.', 'Grandpa''s Inn is a beloved landmark offering excellent value, with rates starting from ₱1,837. Its prime location places it just steps from Calle Crisologo and the Syquia Mansion. The hotel features 26 air-conditioned rooms and 3 on-site restaurants, including the nostalgic Calesa Restaurant built around an actual horse-drawn carriage.', '["budget-friendly", "antique-filled", "nostalgic"]', NULL, 2),
    ('vigan-plaza-hotel', 'stay', 'Vigan Plaza Hotel', 'Mena Crisologo Street, Barangay 2, Vigan City, Ilocos Sur', 'A reliable 3-star hotel with a central location, offering comfortable rooms just steps from the cobblestone streets.', 'Vigan Plaza Hotel is a practical base for travelers. Its prime location puts guests steps away from Calle Crisologo and the Vigan Cathedral. The hotel is about a 5-minute walk from the cathedral and Bantay Bell Tower, and features 29 rooms as well as an on-site restaurant.', '["central", "3-star", "reliable"]', NULL, 3),
    ('calesa', 'transportation', 'Calesa (Horse Carriage)', 'Throughout Vigan City, especially around Calle Crisologo and Plaza Salcedo.', 'A traditional horse-drawn carriage offering the most charming and authentic way to tour Vigan''s historic streets.', 'The calesa is the iconic mode of transport in Vigan City. It''s a must-do experience for any visitor, taking you on a slow journey through the cobblestone lanes of the UNESCO World Heritage Site. Motor vehicles are restricted in the heritage core, allowing you to fully enjoy the horse''s rhythmic clip-clop as you explore.', '["heritage", "tourist attraction", "iconic"]', NULL, 0),
    ('tricycle', 'transportation', 'Tricycle', 'Province-wide', 'A three-wheeled motorcycle with a sidecar, used as the primary "taxi" for getting around towns and cities.', 'The tricycle is the most common mode of public transport within Ilocos Sur and its cities. You can hire them for quick trips to nearby attractions or for longer point-to-point journeys. There are thousands of registered tricycle franchise holders operating in the province, with many also offering day tours for a negotiated rate.', '["local transport", "short trips", "affordable"]', NULL, 1),
    ('jeepney', 'transportation', 'Jeepney', 'Province-wide', 'The iconic Filipino jeepney, used for traveling between cities and municipalities across Ilocos Sur.', 'Jeepneys are a staple for traveling longer distances, such as between Vigan City and other towns and cities in the province. They follow fixed routes and are a very budget-friendly option for getting around. They are one of the three main modes of public transport in the province, alongside buses and tricycles.', '["shared transport", "inter-town", "budget-friendly"]', NULL, 2),
    ('bus-van-terminal', 'transportation', 'Bus & Van Terminals', 'Partas, Dominion, and Viron Transit terminals are located in central Vigan City.', 'Primary gateway for long-haul travel, with terminals offering connections from Manila and key Luzon cities.', 'These are the main hubs for travelers arriving from Metro Manila and other parts of Luzon. Buses are comfortable and fully air-conditioned, with some offering "luxury" services. From these terminals, you can book trips going as far south as Pasay and Cubao in Metro Manila, and as far north as Laoag City. Private vans are also available from these hubs for a faster trip at a slightly higher cost.', '["long haul", "inter-city", "air-conditioned"]', NULL, 3);
